### ISSUE TITLE
Suggestion: An alternative way to obtain historical imdb ratings, via WaybackMachine 

### ISSUE THREAD

**Issue by tuanpham96** [tomstafford/imdb#1]
This is a great delightful result! 

I'm outlining a suggestion to obtain the data. Please let me know if this has been done before, if there's a better way or there are issues with the outlined suggestion.

## General 

**Purpose**: This helps, to some extent, with obtaining the IMDB ratings data, for those who may want to reproduce the results. 

**Approach**: One can use the Internet Archive Wayback Machine to download snapshots of the files. 

**Potential issues**: Not everyday is guaranteed to have a snapshot.

### Requirements

CLI:

- [`aria2`](https://aria2.github.io/) (or `wget`/`curl`)

Python envinronment:

- `pandas`
- `tqdm`
- [`wayback`](https://pypi.org/project/wayback/)

### Organization 

Also the scripts below assume there exists a `data/raw` folder, which contains:
- `links.csv`: CSV file with links to Wayback machine snapshots, and corresponding output files
- `links.aria`: the above file converted into `aria2` input file
- all the snapshots with this file format `YYYYMMDD-HHMMSS-title.ratings.tsv.gz`, in which `YYYYMMDD-HHMMSS` is from the Wayback snapshot's timestamps.

#### Step 1: Obtain snapshot links

Below is content of `get-links.py`

```python
# get-links.py

import os
import wayback
import datetime
from tqdm import tqdm
import pandas as pd

URL = "https://datasets.imdbws.com/title.ratings.tsv.gz"     # URL to find snapshot 
DATA_DIRECTORY = 'data/raw'                                  # where data will be stored
FILENAME_FORMAT = os.path.join(
    DATA_DIRECTORY, 
    '%Y%m%d-%H%M%S-title.ratings.tsv.gz'
)

start_date = datetime.datetime(2023,4,12)                   # from date to find snapshot 
today_date = datetime.datetime.now()
num_days = (today_date - start_date).days

client = wayback.WaybackClient()
links = []

pbar = tqdm(total=num_days, desc='Expected progress')

for r in client.search(URL, from_date=start_date):
    links.append(dict(
        url = r.raw_url, 
        file = r.timestamp.strftime(FILENAME_FORMAT)
    ))
    pbar.update(1)

pbar.close()

pd.DataFrame(links).to_csv(
    os.path.join(DATA_DIRECTORY, 'links.csv'), 
    index=False
)
```

Run with `python get-links.py` (pretty quick)

This will produce `data/raw/links.csv` with the following content

```csv
url,file
https://web.archive.org/web/20230412003412id_/https://datasets.imdbws.com/title.ratings.tsv.gz,data/raw/20230412-003412-title.ratings.tsv.gz
https://web.archive.org/web/20230413003404id_/https://datasets.imdbws.com/title.ratings.tsv.gz,data/raw/20230413-003404-title.ratings.tsv.gz
...
```

#### Step 2: Convert to `aria2` input format 

At this point one can use `aria2`, `curl`, `wget` to download. 

To use `aria2`, the file `links.csv` can be converted to a text file formatted for `aria2`  input:

Run the following code:

```bash
sed 1,1d data/raw/links.csv |\
  sed -E 's/([^,]*),(.*)/\1\n  out=\2/' \
  > data/raw/links.aria 
```

The content of `links.aria` will look like this:

```text
https://web.archive.org/web/20230412003412id_/https://datasets.imdbws.com/title.ratings.tsv.gz
  out=data/raw/20230412-003412-title.ratings.tsv.gz
https://web.archive.org/web/20230413003404id_/https://datasets.imdbws.com/title.ratings.tsv.gz
  out=data/raw/20230413-003404-title.ratings.tsv.gz
```

#### Step 3: Download

```bash
# download files from `links.aria`
aria2c -c -i data/raw/links.aria -j 4

# optional
aria2c https://datasets.imdbws.com/title.basics.tsv.gz -d data/raw
```

Here's how the `data/raw` will look:

```text
data/raw
├── 20230412-003412-title.ratings.tsv.gz
├── 20230413-003404-title.ratings.tsv.gz
├── 20230414-003406-title.ratings.tsv.gz
├── 20230415-003407-title.ratings.tsv.gz
├── 20230416-003534-title.ratings.tsv.gz
├── 20230417-003525-title.ratings.tsv.gz
├── 20230418-003405-title.ratings.tsv.gz
├── 20230419-003405-title.ratings.tsv.gz
├── 20230420-003424-title.ratings.tsv.gz
...

├── links.aria
├── links.csv
└── title.basics.tsv.gz
```

**Comment by tomstafford** [comment]
Excellent - that seems like it would work, and a quick look suggests it would give you 2.5+ years more data. Nice one, and glad you like the project!

**Comment by tomstafford** [comment]
And here's someone who has done something using archive.org https://yathish1618.github.io/imdb-rating-history-graph/
